# Define a 'Persistent Voulume Claim'(PVC) for postgres Storage, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim # name of PVC essential for identifying the storage data
  labels:
    app: postgredb
    tier: database
  namespace: jenkins-3
spec:
  accessModes:
    - ReadWriteOnce   #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 1Gi    #This will tell kubernetes about the amount of space we are trying to claim.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgredb-deployment
  labels:
    app: postgredb
  namespace: jenkins-3
spec:
  replicas: 1
  selector:
    matchLabels: # postgres Pod Should contain same labels
      app: postgredb
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: postgredb
        tier: database
    spec:
      containers:
        - name: postgredb
          image: postgres:15
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgredb-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgredb-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgredb-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
              name: postgredb
          volumeMounts: # Mounting voulume obtained from Persistent Volume Claim
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data #This is the path in the container on which the mounting will take place.
      volumes:
        - name: postgres-persistent-storage  # Obtaining 'vloume' from PVC
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
# Define a 'Service' To Expose postgres to Other Services
apiVersion: v1
kind: Service
metadata:
  name: postgredb-service  # DNS name=
  namespace: jenkins-3
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:       # postgres Pod Should contain same labels
    app: postgredb
    tier: database
 #clusterIP: None  # We Use DNS, Thus ClusterIP is not relevant